### PR TITLE
add quotes to column name

### LINKED ISSUE #10: Package installs correctly, but then all pages display the error (presumably due to config rebuild as `project-config/rebuild` also throws same error):
Experiencing something similar when trying to add Reasons to an existing site. Package installs correctly, but then all pages display the error (presumably due to config rebuild as `project-config/rebuild` also throws same error):

```
error: SQLSTATE[42703]: Undefined column: 7 ERROR:  column reasons.fieldlayoutid does not exist
LINE 3: ...fieldlayouts" "fieldlayouts" ON fieldlayouts.id = reasons.fi...
                                                             ^
HINT:  Perhaps you meant to reference the column "reasons.fieldLayoutId".
The SQL being executed was: SELECT "reasons"."uid", "reasons"."conditionals", "fieldlayouts"."uid" AS "fieldLayoutUid"
FROM "reasons" "reasons"
INNER JOIN "fieldlayouts" "fieldlayouts" ON fieldlayouts.id = reasons.fieldLayoutId
```

Can send through a DB dump and the `config/project` directory if needed 👍

Craft: Pro 3.5.14
Reasons: 2.2.2
DB Engine: PostgreSQL 12.1

_Originally posted by @slavanossar in https://github.com/mmikkel/Reasons-Craft3/issues/9#issuecomment-720216068_

### PR DESCRIPTION
**Pull request by slavanossar**
Fixes https://github.com/mmikkel/Reasons-Craft3/issues/10

### CODE REVIEW

**Comment by mmikkel** [comment]
Thanks a lot for the PR @slavanossar! Unfortunately, your fix breaks MySQL compatibility, so not able to merge.

However, I just pushed a fix that I think might solve your issue. If you're able to test it for me, I'd be very grateful:

`composer require mmikkel/reasons:dev-develop#2cf0b43d54285e456a2a8ce796398c110473b689`

**Comment by slavanossar** [comment]
@mmikkel thanks, I had a feeling my fix might cause something to break. Just tried out your fix and the issue still occurs. Adding quotes to `reasons.fieldLayoutId` doesn't fix it either.

**Comment by mmikkel** [comment]
@slavanossar Thanks for the follow-up! I'll have to dig a bit deeper to figure out a fix that works for both MySQL and Postgres.

**Comment by slavanossar** [comment]
@mmikkel I wanted to figure this out so I set up a couple of test environments with new Craft installs using both MySQL and Postgres, just pushed another update that looks like it works across both.

I verified everything was working correctly by setting up a test section and adding a lightswitch field and a plain text field, was able to edit conditionals in field layout editor and toggling the lightswitch would show/hide the text field as expected.

**Comment by mmikkel** [comment]
Hi @slavanossar – this is awesome, thanks a lot! I'll test your latest commits ASAP 👍

**Comment by slavanossar** [comment]
Just checking in on this, were you able to test it out?

**Comment by mmikkel** [comment]
> Just checking in on this, were you able to test it out?

Sorry, I've been completely swamped. Will get to it ASAP :)

**Comment by slavanossar** [comment]
No worries, take your time. Just wanted to make sure you hadn't forgotten. Thanks!

**Comment by mmikkel** [comment]
Hi @slavanossar, sorry again for being extremely slow on this.    

I tested the latest commits in your PR, but they were causing MySQL exceptions on my end. Ended up fixing the problem in a different way – I just published [Reasons 2.2.3](https://github.com/mmikkel/Reasons-Craft3/releases/tag/2.2.3), which should resolve the issue.

Thanks again for the initial bug report and the PR though!

**Pull request closed without merging**
